version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - nlreturn
    - noinlineerr
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
